apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "helm-platform-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "helm-platform-app.selectorLabels" . | nindent 4 }}
